### ISSUE TITLE
Modulify the Code

### ISSUE THREAD

**Issue by adiXcodr** [adiXcodr/node-ocr#3]
Divide the index.js file in the routes folder into subfiles containing different functions and import the functions in the index file. This will help clean the code

**Comment by Neyen108** [comment]
I want to work on this. Can I?

**Comment by adiXcodr** [comment]
> I want to work on this. Can I?

Okay. Start from 6th

**Comment by PiyushDhamane** [comment]
@adiXcodr I would like to work on this. Please assign this issue to me

**Comment by adiXcodr** [comment]
Go on. I have assigned this issue to someone else before but I'll merge the
one which solves the problem in a better way.

**Comment by adiXcodr** [comment]
Closed with PR #11
