### ISSUE TITLE
Shift API Data storage to MongoDB

### ISSUE THREAD

**Issue by adiXcodr** [adiXcodr/node-ocr#5]
Shift the data write and read for the API keys to MongoDB instead of a local JSON file

**Comment by dramikei** [comment]
Can this be assigned to me?

**Comment by adiXcodr** [comment]
> Can this be assigned to me?

Sure. Go ahead.

**Comment by adiXcodr** [comment]
@dramikei Hey, can you change the mongo uri to an Atlas Cloud one? It would eliminate the need to have mongo installed locally while testing. You can create your own cluster and put the uri for now. I will change the uri later.

**Comment by adiXcodr** [comment]
URI changed to Atlas
