### ISSUE TITLE
Make the app deployable to Heroku

### ISSUE THREAD

**Issue by adiXcodr** [adiXcodr/node-ocr#6]
Add necessary files for Heroku Deployment of the application

**Comment by mousoom** [comment]
i want to work on this issue

**Comment by adiXcodr** [comment]
> i want to work on this issue

Okay

**Comment by dramikei** [comment]
Just a heads up: Though this might be doable, it wouldn't be usable until #5 is done. As you don't have persistent storage on Heroku (local storage gets deleted if the server sleeps OR once every 24 hours)

**Comment by adiXcodr** [comment]
> Just a heads up: Though this might be doable, it wouldn't be usable until #5 is done. As you don't have persistent storage on Heroku (local storage gets deleted if the server sleeps OR once every 24 hours)

Good point. @mousoom Proceed after the data storage is shifted to mongo.

**Comment by adiXcodr** [comment]
Done by @mousoom
